# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestZXCustomTabBar' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestZXCustomTabBar

  pod 'Masonry'
  pod 'SDWebImage'
  target 'TestZXCustomTabBarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestZXCustomTabBarUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
